FROM ruby:3.2.3
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node/Yarn リポジトリ設定
RUN apt-get update -qq \
 && apt-get install -y ca-certificates curl gnupg wget \
 && mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
 && NODE_MAJOR=20 \
 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
 && wget --quiet -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# 開発・テスト用パッケージ + Chromium/Chromedriver
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    nodejs \
    yarn \
    vim \
    wget \
    unzip \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    fonts-liberation \
    xdg-utils \
    chromium \
    chromium-driver \
 && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# 作業ディレクトリ
WORKDIR /sotuapp

# Bundler
RUN gem install bundler

# アプリコピー（先に package.json/yarn.lock をコピーするなら順序入れ替え可）
COPY . /sotuapp

# Frontend ツール
RUN yarn global add esbuild sass
RUN yarn add -D postcss autoprefixer

# 依存インストール
COPY package.json yarn.lock ./
RUN yarn install