# fly.toml app configuration file generated for sotuapp-v2 on 2025-10-11T20:14:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sotuapp-v2'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "bin/rails runner 'puts \"Release phase check: OK\"'"

[env]
  RAILS_ENV = 'production'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'
